### ISSUE TITLE
[Importer] Unknown input file type for "<home_directory>/.flick/emulator-5554/video-emulator-5554-single.mp4"

### ISSUE THREAD

**Issue by pgajeshwar-coupa** [isonic1/flick#33]
I am unable to record video on android emulator.

When I start recording using 'flick video -a start -p android -u emulator-5554' then it shows 'Starting Recoder!!!'. But when I stop recording using command 'flick video -a stop -p android -u emulator-5554' then it throws below error:

```
[Importer] Unknown input file type for "/Users/mymac/.flick/emulator-5554/video-emulator-5554-single.mp4"
Error appending /Users/mymac/.flick/emulator-5554/video-emulator-5554-single.mp4: End Of Stream / File
Saving to /Users/mymac/Project/mobile_automation/end_to_end_tests/emulator-5554.mp4
/Users/mymac/.rvm/gems/ruby-2.4.1@mobile/gems/flick-0.4.2/lib/flick/video.rb:104:in `rename': No such file or directory @ rb_file_s_rename - (/Users/mymac/.flick/emulator-5554/emulator-5554.mp4, /Users/mymac/Project/mobile_automation/end_to_end_tests/emulator-5554.mp4) (Errno::ENOENT)
	from /Users/mymac/.rvm/gems/ruby-2.4.1@mobile/gems/flick-0.4.2/lib/flick/video.rb:104:in `stop_record'
	from /Users/mymac/.rvm/gems/ruby-2.4.1@mobile/gems/flick-0.4.2/lib/flick/video.rb:57:in `stop'
	from /Users/mymac/.rvm/gems/ruby-2.4.1@mobile/gems/flick-0.4.2/lib/flick/video.rb:34:in `run'
	from /Users/mymac/.rvm/gems/ruby-2.4.1@mobile/gems/flick-0.4.2/bin/flick:33:in `block (2 levels) in <top (required)>'
	from /Users/mymac/.rvm/gems/ruby-2.4.1@mobile/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/mymac/.rvm/gems/ruby-2.4.1@mobile/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/mymac/.rvm/gems/ruby-2.4.1@mobile/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/mymac/.rvm/gems/ruby-2.4.1@mobile/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /Users/mymac/.rvm/gems/ruby-2.4.1@mobile/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/mymac/.rvm/gems/ruby-2.4.1@mobile/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'
```

After starting recorder, I can't see flicker process running in the background
`ps -ax | grep flick`
`30338 ttys000    0:00.00 grep flick`

**Comment by isonic1** [comment]
Hi @pgajeshwar-coupa. Can you try updating to the latest version and seeing if that fixes this for you? The version of the gem should be 0.4.3. Thanks.

**Comment by pgajeshwar-coupa** [comment]
Awesome!!! upgrading to 0.4.3 worked. Thanks a lot. :)

**Comment by pgajeshwar-coupa** [comment]
I am again seeing similar problem now.

**Comment by aldochristiaan** [comment]
i got this problem now too ..
even when i tried 0.4.3 version ..
