### ISSUE TITLE
recording not happening

### ISSUE THREAD

**Issue by Jitu1888** [isonic1/flick#48]
Getting the below error:
/Users/jenkins-lab/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/flick-0.4.6/lib/flick/video.rb:104:in `rename': No such file or directory @ rb_file_s_rename - (/Users/jenkins-lab/.flick/1594934708002C0/jitu.mp4, /Users/jenkins-lab/jitu.mp4) (Errno::ENOENT)
	from /Users/jenkins-lab/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/flick-0.4.6/lib/flick/video.rb:104:in `stop_record'
	from /Users/jenkins-lab/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/flick-0.4.6/lib/flick/video.rb:57:in `stop'
	from /Users/jenkins-lab/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/flick-0.4.6/lib/flick/video.rb:34:in `run'
	from /Users/jenkins-lab/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/flick-0.4.6/bin/flick:34:in `block (2 levels) in <top (required)>'
	from /Users/jenkins-lab/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/jenkins-lab/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/jenkins-lab/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/jenkins-lab/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:58:in `run!'
	from /Users/jenkins-lab/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/jenkins-lab/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/import.rb:7:in `block in <top (required)>'

**Comment by Jitu1888** [comment]
@isonic1 Can you please help me out ?
