### ISSUE TITLE
Not able to Stop the service

### ISSUE THREAD

**Issue by saikrishna321** [isonic1/flick#8]
@isonic1 can you please help me on this, when i stop the service it throws the below error

```
flick video -a stop -p android -u FA66VBN01980 -n testing --trace

Stopping Recorder!!!
[iso file] Incomplete box mdat
[iso file] Incomplete MDAT while file is not read-only
No suitable media tracks to cat in /Users/saikrisv/.flick/FA66VBN01980/video-single.mp4 - skipping
Saving to /Users/saikrisv/git/new_appium_parallel/AppiumTestDistribution/testing.mp4
/usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/lib/flick/video.rb:107:in `rename': No such file or directory @ rb_file_s_rename - (/Users/saikrisv/.flick/FA66VBN01980/testing.mp4, /Users/saikrisv/git/new_appium_parallel/AppiumTestDistribution/testing.mp4) (Errno::ENOENT)
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/lib/flick/video.rb:107:in `stop_record'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/lib/flick/video.rb:49:in `stop'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/lib/flick/video.rb:25:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/bin/flick:32:in `block (2 levels) in <top (required)>'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by isonic1** [comment]
Hmm, that is strange. I thought it was working for you. Does this happening when you're running in parallel?

**Comment by saikrishna321** [comment]
no not parallel for now. But wanted to get this within the parallel framework.

This is very flaky at times it works and at times it fails with error

**Comment by saikrishna321** [comment]
@isonic1 i was able to reproduce all time, and did notice the issue. 

when i start the service to record, i don't see the file name video-single.mp4 under the location

/.flick/FA66VBN01980/

Now when i stop the service i get the below exception

```
flick video -a stop -p android -o /Users/saikrisv/git/new_appium_parallel/AppiumTestDistribution/target/screenshot/android/FA66VBN01980/HomePageTest2/testMethodOne_2 -n testMethodOne_2 -u FA66VBN01980 --trace

Stopping Recorder!!!
[iso file] Incomplete box mdat
[iso file] Incomplete MDAT while file is not read-only
No suitable media tracks to cat in /Users/saikrisv/.flick/FA66VBN01980/video-single.mp4 - skipping
Saving to /Users/saikrisv/git/new_appium_parallel/AppiumTestDistribution/target/screenshot/android/FA66VBN01980/HomePageTest2/testMethodOne_2/testMethodOne_2.mp4
/usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/lib/flick/video.rb:107:in `rename': No such file or directory @ rb_file_s_rename - (/Users/saikrisv/.flick/FA66VBN01980/testMethodOne_2.mp4, /Users/saikrisv/git/new_appium_parallel/AppiumTestDistribution/target/screenshot/android/FA66VBN01980/HomePageTest2/testMethodOne_2/testMethodOne_2.mp4) (Errno::ENOENT)
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/lib/flick/video.rb:107:in `stop_record'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/lib/flick/video.rb:49:in `stop'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/lib/flick/video.rb:25:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/flick-0.3.1/bin/flick:32:in `block (2 levels) in <top (required)>'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
```

now the video-single.mp4 file is shown up and running the stop service again it runs fine and the file is pulled to the path

**Comment by saikrishna321** [comment]
@isonic1 more info : works fine on iOS and Android Emulators, fails with the above error when running the recording on real device.

Any help pls

**Comment by saikrishna321** [comment]
@isonic1  ping

**Comment by isonic1** [comment]
Sorry, @saikrishna321. I've been quite busy lately. I will try to take a look at the code tonight and see if I can find where the problem is occurring.

**Comment by saikrishna321** [comment]
@isonic1 Sure .. thanks 👍

**Comment by isonic1** [comment]
So I couldn't ever reproduce the issue you're encountering. At least not with the android phone I have. Unfortunately, I do not have access to any other android phones at the moment. I put in these changes as an extra precaution for race conditions so hopefully maybe that that is what you're encountering.

I'm going to publish these changes soon. Afterwards, please do a "gem uninstall -aIx flick" <-- this will remove all versions of flick. Then do a "gem install flick" which should then be version 0.3.2. Please let me know if this worked for you. Thanks again!

**Comment by saikrishna321** [comment]
sure thing .... ping me once u have it published to gem

**Comment by isonic1** [comment]
The new gem is published. Please give it a go.

**Comment by isonic1** [comment]
@saikrishna321 did this fix your problem?

**Comment by saikrishna321** [comment]
@isonic1 checked with version 0.3.2 and it works. Will report back if any issues running on parallel devices.
